-- SESSION 2

-- postgres=# BEGIN;
-- BEGIN
-- postgres=*# SELECT *
-- postgres-*# FROM pizzeria
-- postgres-*# WHERE name = 'Pizza Hut';
--  id |   name    | rating
-- ----+-----------+--------
--   1 | Pizza Hut |      5
-- (1 row)
-- postgres=*# UPDATE pizzeria
-- postgres-*# SET rating = 3.6
-- postgres-*# WHERE name = 'Pizza Hut';
-- UPDATE 1
-- postgres=*# COMMIT;
-- COMMIT
-- postgres=# SELECT *
-- postgres-# FROM pizzeria
-- postgres-# WHERE name = 'Pizza Hut';
--  id |   name    | rating
-- ----+-----------+--------
--   1 | Pizza Hut |    3.6
-- (1 row)

-- SESSION 1

-- postgres=# BEGIN;
-- BEGIN
-- postgres=*# SELECT *
-- postgres-*# FROM pizzeria
-- postgres-*# WHERE name = 'Pizza Hut'
-- postgres-*# ;
--  id |   name    | rating
-- ----+-----------+--------
--   1 | Pizza Hut |      5
-- (1 row)
-- postgres=*# UPDATE pizzeria
-- postgres-*# SET rating = 4
-- postgres-*# WHERE name = 'Pizza Hut';
-- UPDATE 1
-- postgres=*# COMMIT;
-- COMMIT
-- postgres=# SELECT *
-- postgres-# FROM pizzeria
-- postgres-# WHERE name = 'Pizza Hut';
--  id |   name    | rating
-- ----+-----------+--------
--   1 | Pizza Hut |    3.6
-- (1 row)