-- SESSION 2

-- postgres=# BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
-- BEGIN
-- postgres=*# UPDATE pizzeria
-- postgres-*# SET rating = 3.0
-- postgres-*# WHERE name = 'Pizza Hut';
-- UPDATE 1
-- postgres=*# COMMIT;
-- COMMIT
-- postgres=# SELECT *
-- postgres-# FROM pizzeria
-- postgres-# WHERE name = 'Pizza Hut';
--  id |   name    | rating
-- ----+-----------+--------
--   1 | Pizza Hut |    3.0
-- (1 row)
-- postgres=#

-- SESSION 1 

-- postgres=# BEGIN TRANSACTION ISOLATION LEVEL SERIALIZABLE;
-- BEGIN
-- postgres=*# SELECT *
-- postgres-*# FROM pizzeria
-- postgres-*# WHERE name = 'Pizza Hut';
--  id |   name    | rating
-- ----+-----------+--------
--   1 | Pizza Hut |    3.6
-- (1 row)
-- postgres=*# SELECT *
-- postgres-*# FROM pizzeria
-- postgres-*# WHERE name = 'Pizza Hut';
--  id |   name    | rating
-- ----+-----------+--------
--   1 | Pizza Hut |    3.6
-- (1 row)
-- postgres=*# COMMIT;
-- COMMIT
-- postgres=# SELECT *
-- postgres-# FROM pizzeria
-- postgres-# WHERE name = 'Pizza Hut';
--  id |   name    | rating
-- ----+-----------+--------
--   1 | Pizza Hut |    3.0
-- (1 row)

